using Duende.IdentityServer.EntityFramework.DbContexts;
using Microsoft.EntityFrameworkCore;

namespace IdentityServerProject.Data;

public interface IDatabaseSchemaReadinessValidator
{
    Task EnsureReadyAsync(CancellationToken cancellationToken = default);
}

/// <summary>
///     Performs a read-only migration-history check. Schema changes remain a deployment
///     responsibility; the web process fails closed and never calls Migrate/EnsureCreated.
/// </summary>
public sealed class DatabaseSchemaReadinessValidator(
    ApplicationDbContext applicationDb,
    ConfigurationDbContext configurationDb,
    PersistedGrantDbContext operationalDb,
    ILogger<DatabaseSchemaReadinessValidator> logger) : IDatabaseSchemaReadinessValidator
{
    private readonly ApplicationDbContext _applicationDb = applicationDb;
    private readonly ConfigurationDbContext _configurationDb = configurationDb;
    private readonly ILogger<DatabaseSchemaReadinessValidator> _logger = logger;
    private readonly PersistedGrantDbContext _operationalDb = operationalDb;

    public async Task EnsureReadyAsync(CancellationToken cancellationToken = default)
    {
        await EnsureContextReadyAsync(_applicationDb, nameof(ApplicationDbContext), "identity", cancellationToken);
        await EnsureContextReadyAsync(_configurationDb, nameof(ConfigurationDbContext), "configuration",
            cancellationToken);
        await EnsureContextReadyAsync(_operationalDb, nameof(PersistedGrantDbContext), "operational",
            cancellationToken);
    }

    private async Task EnsureContextReadyAsync(
        DbContext context,
        string contextName,
        string bundleName,
        CancellationToken cancellationToken)
    {
        IReadOnlyList<string> pending;
        try
        {
            pending = (await context.Database.GetPendingMigrationsAsync(cancellationToken)).ToArray();
        }
        catch (Exception ex)
        {
            _logger.LogCritical(
                "Unable to verify the migration state for {DbContext} ({ExceptionType}).",
                contextName,
                ex.GetType().Name);
            throw new InvalidOperationException(
                $"Unable to verify the migration state for {contextName}. " +
                "Run the reviewed migration bundle and verify database connectivity before starting the application.",
                ex);
        }

        if (pending.Count == 0) return;

        _logger.LogCritical(
            "Startup aborted because {DbContext} has {PendingMigrationCount} pending migration(s).",
            contextName,
            pending.Count);
        throw new InvalidOperationException(
            $"{contextName} has pending migrations: {string.Join(", ", pending)}. " +
            $"Run the '{bundleName}' migration bundle generated by scripts/Create-MigrationBundles.ps1 before starting the application.");
    }
}