<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Testing"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Moq"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Sales.Infrastructure\Sales.Infrastructure.csproj"/>
        <ProjectReference Include="..\Sales.ApiService\Sales.ApiService.csproj" Aliases="global,ApiService"/>
        <ProjectReference Include="..\Sales.AppHost\Sales.AppHost.csproj"/>
        <ProjectReference Include="..\IdentityServerProject\src\IdentityServerProject\IdentityServerProject.csproj"/>
        <ProjectReference Include="..\Sales.WasmClient\Sales.WasmClient.csproj"/>
    </ItemGroup>

</Project>
